# vi:ft=ruby:
source 'https://api.berkshelf.com'

def dependencies(path)
  berks = "#{path}/Berksfile.in"
  instance_eval(File.read(berks)) if File.exists?(berks)
end

Dir.glob('./cookbooks/*').each do |path|
  dependencies path
  cookbook File.basename(path), :path => path
end

# PUBLIC COOKBOOKS
cookbook 'getninjas_logstash', git: 'git@bitbucket.org:nullck/getninjas_logstash.git'
cookbook 'logstash', github: 'lusis/chef-logstash'
cookbook 'redis', github: 'phlipper/chef-redis'
